### ISSUE TITLE
Add application insights integration

### ISSUE THREAD

**Issue by timja** [hmcts/expressjs-template#43]

**Comment by linusnorton** [comment]
@timja I was planning to pick up this ticket and do something similar to the [fact frontend](https://github.com/hmcts/fact-frontend/blob/master/src/main/modules/appinsights/index.ts) my only thought was that the app insights key comes in via the properties volume. Should I also integrate that as part of this change or leave it out?

**Comment by timja** [comment]
> @timja I was planning to pick up this ticket and do something similar to the [fact frontend](https://github.com/hmcts/fact-frontend/blob/master/src/main/modules/appinsights/index.ts?rgh-link-date=2020-11-19T09%3A26%3A43Z) my only thought was that the app insights key comes in via the properties volume. Should I also integrate that as part of this change or leave it out?

I would integrate it fully
